"""Predefined milestone catalog embedded in Huckleberry APK 0.9.305."""

from __future__ import annotations

from .models import PredefinedMilestone

# Extracted from assets/public/7417.43e9986c91431da5.js in APK 0.9.305.
PREDEFINED_MILESTONES: tuple[PredefinedMilestone, ...] = (
    PredefinedMilestone(
        id="cdc-2-social-looks-at-your-face",
        age_months=0,
        category="social",
        title="First eye contact",
        typical_window="0–2 weeks",
        source="CDC",
    ),
    PredefinedMilestone(
        id="huckleberry-0-movement-first-finger-grip",
        age_months=0,
        category="movement",
        title="First finger grip",
        typical_window="0–4 weeks",
        source="Huckleberry",
    ),
    PredefinedMilestone(
        id="huckleberry-2-memory-first-night-home",
        age_months=0,
        category="memory",
        title="First night home",
        typical_window="",
        source="Huckleberry",
    ),
    PredefinedMilestone(
        id="huckleberry-2-memory-first-bath",
        age_months=0,
        category="memory",
        title="First bath",
        typical_window="",
        source="Huckleberry",
    ),
    PredefinedMilestone(
        id="huckleberry-2-memory-first-car-ride",
        age_months=0,
        category="memory",
        title="First car ride",
        typical_window="",
        source="Huckleberry",
    ),
    PredefinedMilestone(
        id="huckleberry-2-memory-first-outing",
        age_months=0,
        category="memory",
        title="First outing",
        typical_window="",
        source="Huckleberry",
    ),
    PredefinedMilestone(
        id="huckleberry-0-social-recognizes-your-voice",
        age_months=0,
        category="social",
        title="Recognizes your voice",
        typical_window="1–4 weeks",
        source="Huckleberry",
    ),
    PredefinedMilestone(
        id="huckleberry-0-movement-first-head-lift",
        age_months=0,
        category="movement",
        title="First head lift",
        typical_window="0–4 weeks",
        source="Huckleberry",
    ),
    PredefinedMilestone(
        id="cdc-4-social-smiles-on-his-own-to-get-your-attention",
        age_months=2,
        category="social",
        title="First smile",
        typical_window="1.5–3 months",
        source="CDC",
    ),
    PredefinedMilestone(
        id="cdc-2-movement-holds-head-up-when-on-tummy",
        age_months=2,
        category="movement",
        title="Holds head up during tummy time",
        typical_window="2–4 months",
        source="CDC",
    ),
    PredefinedMilestone(
        id="cdc-4-language-makes-sounds-like-oooo-and-aahh-cooing",
        age_months=2,
        category="language",
        title="First coos",
        typical_window="1.5–3 months",
        source="CDC",
    ),
    PredefinedMilestone(
        id="cdc-2-cognitive-watches-you-as-you-move",
        age_months=2,
        category="cognitive",
        title="Tracks with eyes",
        typical_window="1–3 months",
        source="CDC",
    ),
    PredefinedMilestone(
        id="cdc-6-social-laughs",
        age_months=4,
        category="social",
        title="First laugh",
        typical_window="3–5 months",
        source="CDC",
    ),
    PredefinedMilestone(
        id="cdc-4-language-makes-sounds-back-when-you-talk-to-him",
        age_months=4,
        category="language",
        title="Coos back when you talk",
        typical_window="3–5 months",
        source="CDC",
    ),
    PredefinedMilestone(
        id="cdc-4-movement-uses-his-arm-to-swing-at-toys",
        age_months=4,
        category="movement",
        title="Bats at hanging toys",
        typical_window="3–5 months",
        source="CDC",
    ),
    PredefinedMilestone(
        id="cdc-4-movement-pushes-up-onto-elbows-forearms-when-on-tummy",
        age_months=4,
        category="movement",
        title="Pushes up on elbows",
        typical_window="3–5 months",
        source="CDC",
    ),
    PredefinedMilestone(
        id="huckleberry-4-memory-first-trip",
        age_months=4,
        category="memory",
        title="First trip",
        typical_window="",
        source="Huckleberry",
    ),
    PredefinedMilestone(
        id="huckleberry-4-memory-first-holiday",
        age_months=4,
        category="memory",
        title="First holiday",
        typical_window="",
        source="Huckleberry",
    ),
    PredefinedMilestone(
        id="cdc-6-movement-rolls-from-tummy-to-back",
        age_months=4,
        category="movement",
        title="Rolls over (tummy to back)",
        typical_window="3–6 months",
        source="CDC",
    ),
    PredefinedMilestone(
        id="cdc-6-social-knows-familiar-people",
        age_months=6,
        category="social",
        title="Recognizes familiar faces",
        typical_window="5–7 months",
        source="CDC",
    ),
    PredefinedMilestone(
        id="huckleberry-6-movement-rolls-over-back-to-tummy",
        age_months=6,
        category="movement",
        title="Rolls over (back to tummy)",
        typical_window="3–6 months",
        source="Huckleberry",
    ),
    PredefinedMilestone(
        id="huckleberry-6-movement-sits-with-help",
        age_months=6,
        category="movement",
        title="Sits with help",
        typical_window="5–7 months",
        source="Huckleberry",
    ),
    PredefinedMilestone(
        id="huckleberry-6-memory-first-tooth",
        age_months=6,
        category="memory",
        title="First tooth",
        typical_window="4–8 months",
        source="Huckleberry",
    ),
    PredefinedMilestone(
        id="huckleberry-6-memory-first-swim",
        age_months=6,
        category="memory",
        title="First swim",
        typical_window="",
        source="Huckleberry",
    ),
    PredefinedMilestone(
        id="cdc-6-language-blows-raspberries",
        age_months=6,
        category="language",
        title="Blows raspberries",
        typical_window="5–7 months",
        source="CDC",
    ),
    PredefinedMilestone(
        id="cdc-6-cognitive-reaches-to-grab-a-toy-she-wants",
        age_months=6,
        category="cognitive",
        title="Reaches for toys",
        typical_window="4–6 months",
        source="CDC",
    ),
    PredefinedMilestone(
        id="cdc-9-social-looks-when-you-call-her-name",
        age_months=6,
        category="social",
        title="Responds to name",
        typical_window="5–8 months",
        source="CDC",
    ),
    PredefinedMilestone(
        id="cdc-9-social-is-shy-clingy-or-fearful-around-strangers",
        age_months=9,
        category="social",
        title="Shows stranger anxiety",
        typical_window="6–10 months",
        source="CDC",
    ),
    PredefinedMilestone(
        id="huckleberry-9-movement-crawls",
        age_months=9,
        category="movement",
        title="Crawls",
        typical_window="6–11 months",
        source="Huckleberry",
    ),
    PredefinedMilestone(
        id="huckleberry-9-language-first-babbles",
        age_months=9,
        category="language",
        title="First babbles",
        typical_window="6–10 months",
        source="Huckleberry",
    ),
    PredefinedMilestone(
        id="cdc-9-language-lifts-arms-up-to-be-picked-up",
        age_months=9,
        category="social",
        title="Reaches up to be held",
        typical_window="7–10 months",
        source="CDC",
    ),
    PredefinedMilestone(
        id="cdc-9-movement-sits-without-support",
        age_months=9,
        category="movement",
        title="Sits unassisted",
        typical_window="6–9 months",
        source="CDC",
    ),
    PredefinedMilestone(
        id="cdc-9-social-smiles-or-laughs-when-you-play-peek-a-boo",
        age_months=9,
        category="social",
        title="Plays peek-a-boo",
        typical_window="7–10 months",
        source="CDC",
    ),
    PredefinedMilestone(
        id="cdc-15-movement-uses-fingers-to-feed-herself-some-food",
        age_months=9,
        category="movement",
        title="Feeds self with fingers",
        typical_window="7–10 months",
        source="CDC",
    ),
    PredefinedMilestone(
        id="cdc-18-social-points-to-show-you-something-interesting",
        age_months=9,
        category="language",
        title="Points at objects",
        typical_window="9–12 months",
        source="CDC",
    ),
    PredefinedMilestone(
        id="huckleberry-9-memory-first-birthday-party-attended",
        age_months=9,
        category="memory",
        title="First birthday party attended",
        typical_window="",
        source="Huckleberry",
    ),
    PredefinedMilestone(
        id="cdc-15-language-tries-to-say-one-or-two-words-besides-mama-or-dada",
        age_months=12,
        category="language",
        title="First word",
        typical_window="10–14 months",
        source="CDC",
    ),
    PredefinedMilestone(
        id="huckleberry-12-memory-first-time-sleeping-in-own-room",
        age_months=12,
        category="memory",
        title="First time sleeping in own room",
        typical_window="",
        source="Huckleberry",
    ),
    PredefinedMilestone(
        id="cdc-12-language-calls-a-parent-mama-or-dada-or-another-special-name",
        age_months=12,
        category="language",
        title="Calls caregiver by name",
        typical_window="9–13 months",
        source="CDC",
    ),
    PredefinedMilestone(
        id="cdc-12-language-waves-bye-bye",
        age_months=12,
        category="social",
        title="Waves bye-bye",
        typical_window="9–12 months",
        source="CDC",
    ),
    PredefinedMilestone(
        id="cdc-15-movement-takes-a-few-steps-on-his-own",
        age_months=12,
        category="movement",
        title="First independent steps",
        typical_window="9–18 months",
        source="CDC",
    ),
    PredefinedMilestone(
        id="cdc-12-movement-pulls-up-to-stand",
        age_months=12,
        category="movement",
        title="Pulls up to stand",
        typical_window="8–12 months",
        source="CDC",
    ),
    PredefinedMilestone(
        id="huckleberry-12-movement-stands-unassisted",
        age_months=12,
        category="movement",
        title="Stands unassisted",
        typical_window="9–15 months",
        source="Huckleberry",
    ),
    PredefinedMilestone(
        id="cdc-12-movement-walks-holding-on-to-furniture",
        age_months=12,
        category="movement",
        title="Cruises furniture",
        typical_window="9–15 months",
        source="CDC",
    ),
    PredefinedMilestone(
        id="cdc-12-movement-picks-things-up-between-thumb-and-pointer-finger",
        age_months=12,
        category="movement",
        title="Pincer grasp",
        typical_window="8–12 months",
        source="CDC",
    ),
    PredefinedMilestone(
        id="cdc-15-social-claps-when-excited",
        age_months=15,
        category="social",
        title="Claps hands",
        typical_window="9–15 months",
        source="CDC",
    ),
    PredefinedMilestone(
        id="cdc-18-movement-drinks-from-a-cup-without-a-lid",
        age_months=15,
        category="movement",
        title="Drinks from a cup",
        typical_window="12–18 months",
        source="CDC",
    ),
    PredefinedMilestone(
        id="cdc-15-language-points-to-ask-for-something-or-to-get-help",
        age_months=15,
        category="language",
        title="Points to ask for things",
        typical_window="12–16 months",
        source="CDC",
    ),
    PredefinedMilestone(
        id="cdc-15-social-shows-you-affection",
        age_months=15,
        category="social",
        title="Gives hugs",
        typical_window="12–18 months",
        source="CDC",
    ),
    PredefinedMilestone(
        id="cdc-15-cognitive-stacks-at-least-two-small-objects",
        age_months=15,
        category="cognitive",
        title="Stacks blocks",
        typical_window="12–18 months",
        source="CDC",
    ),
    PredefinedMilestone(
        id="cdc-24-movement-walks-up-a-few-stairs-with-or-without-help",
        age_months=15,
        category="movement",
        title="Climbs stairs",
        typical_window="12–18 months",
        source="CDC",
    ),
    PredefinedMilestone(
        id="huckleberry-18-memory-first-haircut",
        age_months=18,
        category="memory",
        title="First haircut",
        typical_window="",
        source="Huckleberry",
    ),
    PredefinedMilestone(
        id="cdc-18-movement-walks-without-holding-on-to-anyone-or-anything",
        age_months=18,
        category="movement",
        title="Walks on their own",
        typical_window="12–18 months",
        source="CDC",
    ),
    PredefinedMilestone(
        id="cdc-18-movement-scribbles",
        age_months=18,
        category="movement",
        title="First scribbles",
        typical_window="15–18 months",
        source="CDC",
    ),
    PredefinedMilestone(
        id="cdc-18-movement-tries-to-use-a-spoon",
        age_months=18,
        category="movement",
        title="First spoon attempt",
        typical_window="12–18 months",
        source="CDC",
    ),
    PredefinedMilestone(
        id="cdc-18-language-follows-one-step-directions-without-gestures",
        age_months=18,
        category="language",
        title="Follows simple directions",
        typical_window="12–18 months",
        source="CDC",
    ),
    PredefinedMilestone(
        id="cdc-18-cognitive-copies-you-doing-chores",
        age_months=18,
        category="cognitive",
        title="Copies chores",
        typical_window="15–20 months",
        source="CDC",
    ),
    PredefinedMilestone(
        id="cdc-24-language-says-at-least-two-words-together",
        age_months=24,
        category="language",
        title="First two-word phrase",
        typical_window="18–24 months",
        source="CDC",
    ),
    PredefinedMilestone(
        id="cdc-24-movement-runs",
        age_months=24,
        category="movement",
        title="Runs",
        typical_window="18–24 months",
        source="CDC",
    ),
    PredefinedMilestone(
        id="cdc-24-movement-kicks-a-ball",
        age_months=24,
        category="movement",
        title="Kicks a ball",
        typical_window="18–24 months",
        source="CDC",
    ),
    PredefinedMilestone(
        id="cdc-24-movement-eats-with-a-spoon",
        age_months=24,
        category="movement",
        title="Eats with a spoon",
        typical_window="18–24 months",
        source="CDC",
    ),
    PredefinedMilestone(
        id="cdc-30-cognitive-uses-things-to-pretend",
        age_months=24,
        category="cognitive",
        title="First pretend play",
        typical_window="18–24 months",
        source="CDC",
    ),
    PredefinedMilestone(
        id="huckleberry-24-cognitive-stacks-and-sorts-shapes",
        age_months=24,
        category="cognitive",
        title="Stacks and sorts shapes",
        typical_window="18–24 months",
        source="Huckleberry",
    ),
    PredefinedMilestone(
        id="cdc-30-social-plays-next-to-other-children-and-sometimes-plays-with-them",
        age_months=30,
        category="social",
        title="Plays with other kids",
        typical_window="24–30 months",
        source="CDC",
    ),
    PredefinedMilestone(
        id="cdc-30-movement-jumps-off-the-ground-with-both-feet",
        age_months=30,
        category="movement",
        title="Jumps with both feet",
        typical_window="24–30 months",
        source="CDC",
    ),
    PredefinedMilestone(
        id="cdc-30-language-says-two-or-more-words-together-with-one-action-word",
        age_months=30,
        category="language",
        title="First short sentences",
        typical_window="24–30 months",
        source="CDC",
    ),
    PredefinedMilestone(
        id="huckleberry-30-cognitive-names-a-color",
        age_months=30,
        category="cognitive",
        title="Names a color",
        typical_window="24–30 months",
        source="Huckleberry",
    ),
    PredefinedMilestone(
        id="huckleberry-36-memory-moves-to-big-kid-bed",
        age_months=36,
        category="memory",
        title="Moves to big kid bed",
        typical_window="",
        source="Huckleberry",
    ),
    PredefinedMilestone(
        id="cdc-36-language-asks-who-what-where-or-why-questions",
        age_months=36,
        category="language",
        title="Asks 'why' questions",
        typical_window="30–36 months",
        source="CDC",
    ),
    PredefinedMilestone(
        id="cdc-36-cognitive-draws-a-circle-when-shown-how",
        age_months=36,
        category="cognitive",
        title="Draws a circle",
        typical_window="30–36 months",
        source="CDC",
    ),
    PredefinedMilestone(
        id="cdc-18-social-helps-you-dress-him",
        age_months=36,
        category="movement",
        title="Helps get dressed",
        typical_window="30–36 months",
        source="CDC",
    ),
    PredefinedMilestone(
        id="huckleberry-60-social-first-i-love-you",
        age_months=36,
        category="social",
        title="First 'I love you'",
        typical_window="18–36 months",
        source="Huckleberry",
    ),
    PredefinedMilestone(
        id="cdc-48-language-talks-about-at-least-one-thing-that-happened-during-the-day",
        age_months=48,
        category="language",
        title="Talks about their day",
        typical_window="3–4 years",
        source="CDC",
    ),
    PredefinedMilestone(
        id="cdc-48-cognitive-draws-a-person-with-three-or-more-body-parts",
        age_months=48,
        category="cognitive",
        title="Draws a person",
        typical_window="3–5 years",
        source="CDC",
    ),
    PredefinedMilestone(
        id="cdc-48-social-pretends-to-be-something-else-during-play",
        age_months=48,
        category="social",
        title="Plays imaginatively",
        typical_window="2–4 years",
        source="CDC",
    ),
    PredefinedMilestone(
        id="cdc-48-movement-catches-a-large-ball-most-of-the-time",
        age_months=48,
        category="movement",
        title="Catches a ball",
        typical_window="3–5 years",
        source="CDC",
    ),
    PredefinedMilestone(
        id="cdc-48-cognitive-names-a-few-colors-of-items",
        age_months=48,
        category="cognitive",
        title="Names colors",
        typical_window="3–4 years",
        source="CDC",
    ),
    PredefinedMilestone(
        id="cdc-60-cognitive-counts-to-10",
        age_months=60,
        category="cognitive",
        title="Counts to 10",
        typical_window="4–5 years",
        source="CDC",
    ),
    PredefinedMilestone(
        id="cdc-60-cognitive-writes-some-letters-in-her-name",
        age_months=60,
        category="cognitive",
        title="Writes first letters",
        typical_window="4–6 years",
        source="CDC",
    ),
    PredefinedMilestone(
        id="cdc-60-movement-hops-on-one-foot",
        age_months=60,
        category="movement",
        title="Hops on one foot",
        typical_window="4–5 years",
        source="CDC",
    ),
    PredefinedMilestone(
        id="cdc-60-social-follows-rules-or-takes-turns-when-playing-games-with-other-children",
        age_months=60,
        category="social",
        title="Takes turns",
        typical_window="4–5 years",
        source="CDC",
    ),
    PredefinedMilestone(
        id="cdc-60-language-tells-a-story-with-at-least-two-events",
        age_months=60,
        category="language",
        title="Tells a full story",
        typical_window="4–5 years",
        source="CDC",
    ),
    PredefinedMilestone(
        id="huckleberry-60-memory-first-day-of-school",
        age_months=60,
        category="memory",
        title="First day of school",
        typical_window="",
        source="Huckleberry",
    ),
)

PREDEFINED_MILESTONES_BY_ID = {milestone.id: milestone for milestone in PREDEFINED_MILESTONES}
